name: Run tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Install and test
      uses: s-weigand/setup-conda@v1
      with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      run: |
        conda env update -f requirements.txt
        conda env update -f requirements_dev.txt
        pytest
